language: ruby

rvm:
  - 2.2.3

branches:
  only:
    - master

script:
  - "echo ${GH_TOKEN} > ./.git/credentials"
  - "git config --global user.name Travis"
  - "git config --global user.email travis@travis-ci.org"
  - "git remote set-url origin \"https://${GH_TOKEN}@github.com/thearrow/hhfarm.git\""
  - "bundle exec middleman deploy"